data:
  dataset:
    name: pressure1 # choices are ['pressure1', 'pressure2', 'pressure3', 'pressure4']
    root_path: /home/lab-wu.shibin/SFDA/data/pressure1 # /path/to/dataset/root
    source: 0 # source domain index
    target: 1 # target domain index

  dataloader:
    class_balance: true #
    data_workers: 4 # how many workers to use for train dataloaders
    batch_size: 32 # batch_size for source domain and target domain respectively

model:
  base_model: resnet50 # choices=['resnet50', 'vgg16']
  pretrained_model:  # /path/to/pretrained/model
  bottle_neck_dim: 2048

train:
  min_step: 20000 # minimum steps to run. run epochs until it exceeds the minStep
  iters_per_epoch: 100
  lr: 0.001 # learning rate for new layers. learning rate for finetune is 1/10 of lr
  weight_decay: 0.002
  momentum: 0.95
  SF_weight: 1
  DA_weight: 1
  num_class: 2

test:
  test_interval: 500 # interval of two continuous test phase
  test_only: True # test a given model and exit
  resume_file: /home/lab-wu.shibin/SFDA/log/saving_time/saving_model

misc:
  gpus: 1 # how many GPUs to be used, 0 indicates CPU only

log:
  root_dir: log # the log directory (log directory will be {root_dir}/{method}/time/)
  log_interval: 10 # steps to log scalars
